[package]
name = "hello-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "hello_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
regex = "1.10.2"
itertools = "0.12.0"
num = "0.4.1"
